
CREATE TABLE DISCIPLINE
(
	ID_DISCIPLINE        INT(12) NOT NULL AUTO_INCREMENT,
	TX_NAME              VARCHAR(30) NOT NULL
);



CREATE UNIQUE INDEX XPKDISCIPLINE ON DISCIPLINE
(
	ID_DISCIPLINE
);



ALTER TABLE DISCIPLINE
ADD PRIMARY KEY (ID_DISCIPLINE);



CREATE TABLE TB_CIA
(
	ID_CIA               INT(12) NOT NULL AUTO_INCREMENT,
	TX_ADDRESS           VARCHAR(255) NULL,
	NM_CITY              VARCHAR(30) NOT NULL,
	TX_ZIP_CODE          VARCHAR(10) NOT NULL,
	TX_TIN               VARCHAR(10) NULL
);



CREATE UNIQUE INDEX XPKCIA ON TB_CIA
(
	ID_CIA
);



ALTER TABLE TB_CIA
ADD PRIMARY KEY (ID_CIA);



CREATE TABLE TB_CONTACT_PERSON
(
	ID_CONTACT_PERSON    INT(12) NOT NULL AUTO_INCREMENT,
	TX_NAME              VARCHAR(60) NOT NULL,
	TX_MAIL              VARCHAR(60) NOT NULL,
	TX_MOBILE            VARCHAR(10) NULL
);



CREATE UNIQUE INDEX XPKCONTACT_PERSON ON TB_CONTACT_PERSON
(
	ID_CONTACT_PERSON
);



ALTER TABLE TB_CONTACT_PERSON
ADD PRIMARY KEY (ID_CONTACT_PERSON);



CREATE TABLE TB_GOAL
(
	ID_GOAL              INT(12) NOT NULL AUTO_INCREMENT,
	ID_PROJECT           INT(12) NOT NULL,
	ID_POTENCIAL_USE     INT(12) NOT NULL,
	ID_DISCIPLINE        INT(12) NOT NULL,
	DS_DESCRIPTION       VARCHAR(255) NOT NULL,
	IN_PRIORITY          VARCHAR(255) NULL
);



CREATE UNIQUE INDEX XPKGOAL ON TB_GOAL
(
	ID_GOAL
);



ALTER TABLE TB_GOAL
ADD PRIMARY KEY (ID_GOAL);



CREATE INDEX XIF1GOAL ON TB_GOAL
(
	ID_DISCIPLINE
);



CREATE INDEX XIF2GOAL ON TB_GOAL
(
	ID_POTENCIAL_USE
);



CREATE INDEX XIF3GOAL ON TB_GOAL
(
	ID_PROJECT
);



CREATE TABLE TB_HARDWARE
(
	ID_HARDWARE          INT(12) NOT NULL AUTO_INCREMENT,
	ID_PROJECT           INT(12) NOT NULL,
	ID_HARDWARE_TYPE     INT(12) NOT NULL,
	DS_DESCRIPTION       VARCHAR(255) NULL
);



CREATE UNIQUE INDEX XPKHARDWARE ON TB_HARDWARE
(
	ID_HARDWARE
);



ALTER TABLE TB_HARDWARE
ADD PRIMARY KEY (ID_HARDWARE);



CREATE INDEX XIF1HARDWARE ON TB_HARDWARE
(
	ID_HARDWARE_TYPE
);



CREATE INDEX XIF2HARDWARE ON TB_HARDWARE
(
	ID_PROJECT
);



CREATE TABLE TB_HARDWARE_TYPE
(
	ID_HARDWARE_TYPE     INT(12) NOT NULL AUTO_INCREMENT,
	NM_NAME              VARCHAR(60) NOT NULL
);



CREATE UNIQUE INDEX XPKHARDWARE_TYPE ON TB_HARDWARE_TYPE
(
	ID_HARDWARE_TYPE
);



ALTER TABLE TB_HARDWARE_TYPE
ADD PRIMARY KEY (ID_HARDWARE_TYPE);



CREATE TABLE TB_INVITE
(
	ID_INVITE            INT(12) NOT NULL AUTO_INCREMENT,
	ID_CONTACT_PERSON    INT(12) NOT NULL,
	ID_PROJECT           INT(12) NOT NULL,
	CD_INVITE            VARCHAR(6) NOT NULL
);



CREATE UNIQUE INDEX XPKINVITE ON TB_INVITE
(
	ID_INVITE
);



ALTER TABLE TB_INVITE
ADD PRIMARY KEY (ID_INVITE);



CREATE INDEX XIF1INVITE ON TB_INVITE
(
	ID_PROJECT
);



CREATE INDEX XIF2INVITE ON TB_INVITE
(
	ID_CONTACT_PERSON
);



CREATE TABLE TB_KEY_MEMBER
(
	ID_KEY_MEMBER        INT(12) NOT NULL AUTO_INCREMENT,
	ID_PROJECT           INT(12) NOT NULL,
	ID_CONTACT_PERSON    INT(12) NOT NULL,
	ID_CIA               INT(12) NOT NULL,
	ID_DISCIPLINE        INT(12) NOT NULL
);



CREATE UNIQUE INDEX XPKKEY_MEMBER ON TB_KEY_MEMBER
(
	ID_KEY_MEMBER
);



ALTER TABLE TB_KEY_MEMBER
ADD PRIMARY KEY (ID_KEY_MEMBER);



CREATE INDEX XIF1KEY_MEMBER ON TB_KEY_MEMBER
(
	ID_DISCIPLINE
);



CREATE INDEX XIF2KEY_MEMBER ON TB_KEY_MEMBER
(
	ID_CIA
);



CREATE INDEX XIF3KEY_MEMBER ON TB_KEY_MEMBER
(
	ID_CONTACT_PERSON
);



CREATE INDEX XIF4KEY_MEMBER ON TB_KEY_MEMBER
(
	ID_PROJECT
);



CREATE TABLE TB_POTENTICAL_USE
(
	ID_POTENCIAL_USE     INT(12) NOT NULL AUTO_INCREMENT,
	TX_NAME              VARCHAR(60) NOT NULL
);



CREATE UNIQUE INDEX XPKPOTENTICAL_USE ON TB_POTENTICAL_USE
(
	ID_POTENCIAL_USE
);



ALTER TABLE TB_POTENTICAL_USE
ADD PRIMARY KEY (ID_POTENCIAL_USE);



CREATE TABLE TB_PROJECT
(
	ID_PROJECT           INT(12) NOT NULL AUTO_INCREMENT,
	ID_USER              INT(12) NOT NULL,
	ID_CONTACT_PERSON_ADMIN INT(12) NOT NULL,
	NR_VERSION           VARCHAR(2) NOT NULL,
	DT_LAST_UPDATE       TIMESTAMP NOT NULL,
	DS_OVERVIEW          VARCHAR(4000) NOT NULL,
	TX_NAME              VARCHAR(60) NOT NULL,
	TX_LOCATION          VARCHAR(255) NULL
);



CREATE UNIQUE INDEX XPKPROJECT ON TB_PROJECT
(
	ID_PROJECT
);



ALTER TABLE TB_PROJECT
ADD PRIMARY KEY (ID_PROJECT);



CREATE INDEX XIF1PROJECT ON TB_PROJECT
(
	ID_CONTACT_PERSON_ADMIN
);



CREATE INDEX XIF2PROJECT ON TB_PROJECT
(
	ID_USER
);



CREATE TABLE TB_PROJECT_CIA
(
	ID_PROJECT_CIA       INT(12) NOT NULL AUTO_INCREMENT,
	ID_CIA               INT(12) NOT NULL,
	ID_PROJECT           INT(12) NOT NULL
);



CREATE UNIQUE INDEX XPKPROJECT_CIA ON TB_PROJECT_CIA
(
	ID_PROJECT_CIA
);



ALTER TABLE TB_PROJECT_CIA
ADD PRIMARY KEY (ID_PROJECT_CIA);



CREATE INDEX XIF1PROJECT_CIA ON TB_PROJECT_CIA
(
	ID_PROJECT
);



CREATE INDEX XIF2PROJECT_CIA ON TB_PROJECT_CIA
(
	ID_CIA
);



CREATE TABLE TB_SOFTWARE
(
	ID_SOFTWARE          INT(12) NOT NULL AUTO_INCREMENT,
	ID_PROJECT           INT(12) NOT NULL,
	ID_SOFTWARE_TYPE     INT(12) NOT NULL,
	DS_DESCRIPTION       VARCHAR(255) NULL
);



CREATE UNIQUE INDEX XPKSOFTWARE ON TB_SOFTWARE
(
	ID_SOFTWARE
);



ALTER TABLE TB_SOFTWARE
ADD PRIMARY KEY (ID_SOFTWARE);



CREATE INDEX XIF1SOFTWARE ON TB_SOFTWARE
(
	ID_SOFTWARE_TYPE
);



CREATE INDEX XIF2SOFTWARE ON TB_SOFTWARE
(
	ID_PROJECT
);



CREATE TABLE TB_SOFTWARE_TYPE
(
	ID_SOFTWARE_TYPE     INT(12) NOT NULL AUTO_INCREMENT,
	NM_NAME              VARCHAR(255) NULL
);



CREATE UNIQUE INDEX XPKSOFTWARE_TYPE ON TB_SOFTWARE_TYPE
(
	ID_SOFTWARE_TYPE
);



ALTER TABLE TB_SOFTWARE_TYPE
ADD PRIMARY KEY (ID_SOFTWARE_TYPE);



CREATE TABLE USER
(
	ID_USER              INT(12) NOT NULL AUTO_INCREMENT,
	TX_MAIL              VARCHAR(60) NOT NULL,
	TX_PASSWORD          VARCHAR(255) NOT NULL
);



CREATE UNIQUE INDEX XPKUSER ON USER
(
	ID_USER
);



ALTER TABLE USER
ADD PRIMARY KEY (ID_USER);



ALTER TABLE TB_GOAL
ADD (ID_DISCIPLINE) REFERENCES DISCIPLINE (ID_DISCIPLINE);



ALTER TABLE TB_GOAL
ADD (ID_POTENCIAL_USE) REFERENCES TB_POTENTICAL_USE (ID_POTENCIAL_USE);



ALTER TABLE TB_GOAL
ADD (ID_PROJECT) REFERENCES TB_PROJECT (ID_PROJECT);



ALTER TABLE TB_HARDWARE
ADD (ID_HARDWARE_TYPE) REFERENCES TB_HARDWARE_TYPE (ID_HARDWARE_TYPE);



ALTER TABLE TB_HARDWARE
ADD (ID_PROJECT) REFERENCES TB_PROJECT (ID_PROJECT);



ALTER TABLE TB_INVITE
ADD (ID_PROJECT) REFERENCES TB_PROJECT (ID_PROJECT);



ALTER TABLE TB_INVITE
ADD (ID_CONTACT_PERSON) REFERENCES TB_CONTACT_PERSON (ID_CONTACT_PERSON);



ALTER TABLE TB_KEY_MEMBER
ADD (ID_DISCIPLINE) REFERENCES DISCIPLINE (ID_DISCIPLINE);



ALTER TABLE TB_KEY_MEMBER
ADD (ID_CIA) REFERENCES TB_CIA (ID_CIA);



ALTER TABLE TB_KEY_MEMBER
ADD (ID_CONTACT_PERSON) REFERENCES TB_CONTACT_PERSON (ID_CONTACT_PERSON);



ALTER TABLE TB_KEY_MEMBER
ADD (ID_PROJECT) REFERENCES TB_PROJECT (ID_PROJECT);



ALTER TABLE TB_PROJECT
ADD (ID_CONTACT_PERSON_ADMIN) REFERENCES TB_CONTACT_PERSON (ID_CONTACT_PERSON);



ALTER TABLE TB_PROJECT
ADD (ID_USER) REFERENCES USER (ID_USER);



ALTER TABLE TB_PROJECT_CIA
ADD (ID_PROJECT) REFERENCES TB_PROJECT (ID_PROJECT);



ALTER TABLE TB_PROJECT_CIA
ADD (ID_CIA) REFERENCES TB_CIA (ID_CIA);



ALTER TABLE TB_SOFTWARE
ADD (ID_SOFTWARE_TYPE) REFERENCES TB_SOFTWARE_TYPE (ID_SOFTWARE_TYPE);



ALTER TABLE TB_SOFTWARE
ADD (ID_PROJECT) REFERENCES TB_PROJECT (ID_PROJECT);


