//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}DomainProps"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Constraint_State_Groups" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Check_Constraint_Usage_Groups" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Default_Constraint_Usage_Groups" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domainProps",
    "oracleConstraintStateGroups",
    "checkConstraintUsageGroups",
    "defaultConstraintUsageGroups"
})
@XmlRootElement(name = "Domain")
public class Domain {

    @XmlElement(name = "DomainProps", required = true)
    protected DomainProps domainProps;
    @XmlElement(name = "Oracle_Constraint_State_Groups")
    protected OracleConstraintStateGroups oracleConstraintStateGroups;
    @XmlElement(name = "Check_Constraint_Usage_Groups")
    protected CheckConstraintUsageGroups checkConstraintUsageGroups;
    @XmlElement(name = "Default_Constraint_Usage_Groups")
    protected DefaultConstraintUsageGroups defaultConstraintUsageGroups;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the domainProps property.
     * 
     * @return
     *     possible object is
     *     {@link DomainProps }
     *     
     */
    public DomainProps getDomainProps() {
        return domainProps;
    }

    /**
     * Sets the value of the domainProps property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainProps }
     *     
     */
    public void setDomainProps(DomainProps value) {
        this.domainProps = value;
    }

    /**
     * Gets the value of the oracleConstraintStateGroups property.
     * 
     * @return
     *     possible object is
     *     {@link OracleConstraintStateGroups }
     *     
     */
    public OracleConstraintStateGroups getOracleConstraintStateGroups() {
        return oracleConstraintStateGroups;
    }

    /**
     * Sets the value of the oracleConstraintStateGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link OracleConstraintStateGroups }
     *     
     */
    public void setOracleConstraintStateGroups(OracleConstraintStateGroups value) {
        this.oracleConstraintStateGroups = value;
    }

    /**
     * Gets the value of the checkConstraintUsageGroups property.
     * 
     * @return
     *     possible object is
     *     {@link CheckConstraintUsageGroups }
     *     
     */
    public CheckConstraintUsageGroups getCheckConstraintUsageGroups() {
        return checkConstraintUsageGroups;
    }

    /**
     * Sets the value of the checkConstraintUsageGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckConstraintUsageGroups }
     *     
     */
    public void setCheckConstraintUsageGroups(CheckConstraintUsageGroups value) {
        this.checkConstraintUsageGroups = value;
    }

    /**
     * Gets the value of the defaultConstraintUsageGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultConstraintUsageGroups }
     *     
     */
    public DefaultConstraintUsageGroups getDefaultConstraintUsageGroups() {
        return defaultConstraintUsageGroups;
    }

    /**
     * Sets the value of the defaultConstraintUsageGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultConstraintUsageGroups }
     *     
     */
    public void setDefaultConstraintUsageGroups(DefaultConstraintUsageGroups value) {
        this.defaultConstraintUsageGroups = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
