//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.ca.com/erwin/data}Built_In_Id"/>
 *           &lt;element ref="{http://www.ca.com/erwin/data}Definition"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Type"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Note" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.ca.com/erwin/data}Physical_Data_Type"/>
 *           &lt;element ref="{http://www.ca.com/erwin/data}Icon_Ref"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Null_Option_Type"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Comment" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Logical_Data_Type"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Parent_Domain_Ref" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Constraint_State_Ref" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Attribute_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Column_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Attribute_Definition" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Column_Comment"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Attribute_Icon_Ref" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Attribute_Note" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Prohibit_Check_Constraint_Inheritance" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Prohibit_Default_Constraint_Inheritance" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "builtInId",
    "definition",
    "name",
    "longId",
    "ownerPath",
    "type",
    "note",
    "physicalDataType",
    "iconRef",
    "nullOptionType",
    "comment",
    "physicalName",
    "logicalDataType",
    "parentDomainRef",
    "oracleConstraintStateRef",
    "dependentObjectsRefArray",
    "attributeName",
    "columnName",
    "attributeDefinition",
    "columnComment",
    "attributeIconRef",
    "attributeNote",
    "userFormattedName",
    "userFormattedPhysicalName",
    "prohibitCheckConstraintInheritance",
    "prohibitDefaultConstraintInheritance"
})
@XmlRootElement(name = "DomainProps")
public class DomainProps {

    @XmlElement(name = "Built_In_Id")
    protected BigInteger builtInId;
    @XmlElement(name = "Definition")
    protected Definition definition;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Type", required = true)
    protected Type type;
    @XmlElement(name = "Note")
    protected Note note;
    @XmlElement(name = "Physical_Data_Type")
    protected PhysicalDataType physicalDataType;
    @XmlElement(name = "Icon_Ref")
    protected IconRef iconRef;
    @XmlElement(name = "Null_Option_Type", required = true)
    protected NullOptionType nullOptionType;
    @XmlElement(name = "Comment")
    protected Comment comment;
    @XmlElement(name = "Physical_Name", required = true)
    protected PhysicalName physicalName;
    @XmlElement(name = "Logical_Data_Type", required = true)
    protected LogicalDataType logicalDataType;
    @XmlElement(name = "Parent_Domain_Ref")
    protected ParentDomainRef parentDomainRef;
    @XmlElement(name = "Oracle_Constraint_State_Ref")
    protected String oracleConstraintStateRef;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "Attribute_Name", required = true)
    protected AttributeName attributeName;
    @XmlElement(name = "Column_Name", required = true)
    protected ColumnName columnName;
    @XmlElement(name = "Attribute_Definition")
    protected String attributeDefinition;
    @XmlElement(name = "Column_Comment", required = true)
    protected ColumnComment columnComment;
    @XmlElement(name = "Attribute_Icon_Ref")
    protected AttributeIconRef attributeIconRef;
    @XmlElement(name = "Attribute_Note")
    protected String attributeNote;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;
    @XmlElement(name = "Prohibit_Check_Constraint_Inheritance")
    protected Boolean prohibitCheckConstraintInheritance;
    @XmlElement(name = "Prohibit_Default_Constraint_Inheritance")
    protected Boolean prohibitDefaultConstraintInheritance;

    /**
     * Gets the value of the builtInId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBuiltInId() {
        return builtInId;
    }

    /**
     * Sets the value of the builtInId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBuiltInId(BigInteger value) {
        this.builtInId = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link Definition }
     *     
     */
    public Definition getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition }
     *     
     */
    public void setDefinition(Definition value) {
        this.definition = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Note }
     *     
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Note }
     *     
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the physicalDataType property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalDataType }
     *     
     */
    public PhysicalDataType getPhysicalDataType() {
        return physicalDataType;
    }

    /**
     * Sets the value of the physicalDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalDataType }
     *     
     */
    public void setPhysicalDataType(PhysicalDataType value) {
        this.physicalDataType = value;
    }

    /**
     * Gets the value of the iconRef property.
     * 
     * @return
     *     possible object is
     *     {@link IconRef }
     *     
     */
    public IconRef getIconRef() {
        return iconRef;
    }

    /**
     * Sets the value of the iconRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link IconRef }
     *     
     */
    public void setIconRef(IconRef value) {
        this.iconRef = value;
    }

    /**
     * Gets the value of the nullOptionType property.
     * 
     * @return
     *     possible object is
     *     {@link NullOptionType }
     *     
     */
    public NullOptionType getNullOptionType() {
        return nullOptionType;
    }

    /**
     * Sets the value of the nullOptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullOptionType }
     *     
     */
    public void setNullOptionType(NullOptionType value) {
        this.nullOptionType = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the physicalName property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalName }
     *     
     */
    public PhysicalName getPhysicalName() {
        return physicalName;
    }

    /**
     * Sets the value of the physicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalName }
     *     
     */
    public void setPhysicalName(PhysicalName value) {
        this.physicalName = value;
    }

    /**
     * Gets the value of the logicalDataType property.
     * 
     * @return
     *     possible object is
     *     {@link LogicalDataType }
     *     
     */
    public LogicalDataType getLogicalDataType() {
        return logicalDataType;
    }

    /**
     * Sets the value of the logicalDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicalDataType }
     *     
     */
    public void setLogicalDataType(LogicalDataType value) {
        this.logicalDataType = value;
    }

    /**
     * Gets the value of the parentDomainRef property.
     * 
     * @return
     *     possible object is
     *     {@link ParentDomainRef }
     *     
     */
    public ParentDomainRef getParentDomainRef() {
        return parentDomainRef;
    }

    /**
     * Sets the value of the parentDomainRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentDomainRef }
     *     
     */
    public void setParentDomainRef(ParentDomainRef value) {
        this.parentDomainRef = value;
    }

    /**
     * Gets the value of the oracleConstraintStateRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOracleConstraintStateRef() {
        return oracleConstraintStateRef;
    }

    /**
     * Sets the value of the oracleConstraintStateRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOracleConstraintStateRef(String value) {
        this.oracleConstraintStateRef = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the attributeName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeName }
     *     
     */
    public AttributeName getAttributeName() {
        return attributeName;
    }

    /**
     * Sets the value of the attributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeName }
     *     
     */
    public void setAttributeName(AttributeName value) {
        this.attributeName = value;
    }

    /**
     * Gets the value of the columnName property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnName }
     *     
     */
    public ColumnName getColumnName() {
        return columnName;
    }

    /**
     * Sets the value of the columnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnName }
     *     
     */
    public void setColumnName(ColumnName value) {
        this.columnName = value;
    }

    /**
     * Gets the value of the attributeDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeDefinition() {
        return attributeDefinition;
    }

    /**
     * Sets the value of the attributeDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeDefinition(String value) {
        this.attributeDefinition = value;
    }

    /**
     * Gets the value of the columnComment property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnComment }
     *     
     */
    public ColumnComment getColumnComment() {
        return columnComment;
    }

    /**
     * Sets the value of the columnComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnComment }
     *     
     */
    public void setColumnComment(ColumnComment value) {
        this.columnComment = value;
    }

    /**
     * Gets the value of the attributeIconRef property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeIconRef }
     *     
     */
    public AttributeIconRef getAttributeIconRef() {
        return attributeIconRef;
    }

    /**
     * Sets the value of the attributeIconRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeIconRef }
     *     
     */
    public void setAttributeIconRef(AttributeIconRef value) {
        this.attributeIconRef = value;
    }

    /**
     * Gets the value of the attributeNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeNote() {
        return attributeNote;
    }

    /**
     * Sets the value of the attributeNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeNote(String value) {
        this.attributeNote = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

    /**
     * Gets the value of the prohibitCheckConstraintInheritance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProhibitCheckConstraintInheritance() {
        return prohibitCheckConstraintInheritance;
    }

    /**
     * Sets the value of the prohibitCheckConstraintInheritance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProhibitCheckConstraintInheritance(Boolean value) {
        this.prohibitCheckConstraintInheritance = value;
    }

    /**
     * Gets the value of the prohibitDefaultConstraintInheritance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProhibitDefaultConstraintInheritance() {
        return prohibitDefaultConstraintInheritance;
    }

    /**
     * Sets the value of the prohibitDefaultConstraintInheritance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProhibitDefaultConstraintInheritance(Boolean value) {
        this.prohibitDefaultConstraintInheritance = value;
    }

}
