//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Built_In_Id" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Font_Type_Face"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Font_Size"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Font_Bold"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Font_Italic"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Font_Underlined"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Font_Strikeout"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "builtInId",
    "name",
    "longId",
    "ownerPath",
    "fontTypeFace",
    "fontSize",
    "isFontBold",
    "isFontItalic",
    "isFontUnderlined",
    "isFontStrikeout",
    "dependentObjectsRefArray",
    "userFormattedName",
    "userFormattedPhysicalName"
})
@XmlRootElement(name = "FontProps")
public class FontProps {

    @XmlElement(name = "Built_In_Id")
    protected BigInteger builtInId;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Font_Type_Face", required = true)
    protected String fontTypeFace;
    @XmlElement(name = "Font_Size", required = true)
    protected BigInteger fontSize;
    @XmlElement(name = "Is_Font_Bold")
    protected boolean isFontBold;
    @XmlElement(name = "Is_Font_Italic")
    protected boolean isFontItalic;
    @XmlElement(name = "Is_Font_Underlined")
    protected boolean isFontUnderlined;
    @XmlElement(name = "Is_Font_Strikeout")
    protected boolean isFontStrikeout;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;

    /**
     * Gets the value of the builtInId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBuiltInId() {
        return builtInId;
    }

    /**
     * Sets the value of the builtInId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBuiltInId(BigInteger value) {
        this.builtInId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the fontTypeFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontTypeFace() {
        return fontTypeFace;
    }

    /**
     * Sets the value of the fontTypeFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontTypeFace(String value) {
        this.fontTypeFace = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFontSize(BigInteger value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the isFontBold property.
     * 
     */
    public boolean isIsFontBold() {
        return isFontBold;
    }

    /**
     * Sets the value of the isFontBold property.
     * 
     */
    public void setIsFontBold(boolean value) {
        this.isFontBold = value;
    }

    /**
     * Gets the value of the isFontItalic property.
     * 
     */
    public boolean isIsFontItalic() {
        return isFontItalic;
    }

    /**
     * Sets the value of the isFontItalic property.
     * 
     */
    public void setIsFontItalic(boolean value) {
        this.isFontItalic = value;
    }

    /**
     * Gets the value of the isFontUnderlined property.
     * 
     */
    public boolean isIsFontUnderlined() {
        return isFontUnderlined;
    }

    /**
     * Sets the value of the isFontUnderlined property.
     * 
     */
    public void setIsFontUnderlined(boolean value) {
        this.isFontUnderlined = value;
    }

    /**
     * Gets the value of the isFontStrikeout property.
     * 
     */
    public boolean isIsFontStrikeout() {
        return isFontStrikeout;
    }

    /**
     * Sets the value of the isFontStrikeout property.
     * 
     */
    public void setIsFontStrikeout(boolean value) {
        this.isFontStrikeout = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

}
