//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Attribute_Ref"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Key_Group_Sort_Order"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Parent_Key_Group_Member_Ref" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Index_Member_Order"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Key_Group_Member_Order"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "longId",
    "ownerPath",
    "attributeRef",
    "keyGroupSortOrder",
    "physicalName",
    "dependentObjectsRefArray",
    "parentKeyGroupMemberRef",
    "userFormattedName",
    "userFormattedPhysicalName",
    "indexMemberOrder",
    "keyGroupMemberOrder"
})
@XmlRootElement(name = "Key_Group_MemberProps")
public class KeyGroupMemberProps {

    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Attribute_Ref", required = true)
    protected String attributeRef;
    @XmlElement(name = "Key_Group_Sort_Order", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String keyGroupSortOrder;
    @XmlElement(name = "Physical_Name", required = true)
    protected PhysicalName physicalName;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "Parent_Key_Group_Member_Ref")
    protected String parentKeyGroupMemberRef;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;
    @XmlElement(name = "Index_Member_Order", required = true)
    protected IndexMemberOrder indexMemberOrder;
    @XmlElement(name = "Key_Group_Member_Order", required = true)
    protected KeyGroupMemberOrder keyGroupMemberOrder;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the attributeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeRef() {
        return attributeRef;
    }

    /**
     * Sets the value of the attributeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeRef(String value) {
        this.attributeRef = value;
    }

    /**
     * Gets the value of the keyGroupSortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyGroupSortOrder() {
        return keyGroupSortOrder;
    }

    /**
     * Sets the value of the keyGroupSortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyGroupSortOrder(String value) {
        this.keyGroupSortOrder = value;
    }

    /**
     * Gets the value of the physicalName property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalName }
     *     
     */
    public PhysicalName getPhysicalName() {
        return physicalName;
    }

    /**
     * Sets the value of the physicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalName }
     *     
     */
    public void setPhysicalName(PhysicalName value) {
        this.physicalName = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the parentKeyGroupMemberRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentKeyGroupMemberRef() {
        return parentKeyGroupMemberRef;
    }

    /**
     * Sets the value of the parentKeyGroupMemberRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentKeyGroupMemberRef(String value) {
        this.parentKeyGroupMemberRef = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

    /**
     * Gets the value of the indexMemberOrder property.
     * 
     * @return
     *     possible object is
     *     {@link IndexMemberOrder }
     *     
     */
    public IndexMemberOrder getIndexMemberOrder() {
        return indexMemberOrder;
    }

    /**
     * Sets the value of the indexMemberOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexMemberOrder }
     *     
     */
    public void setIndexMemberOrder(IndexMemberOrder value) {
        this.indexMemberOrder = value;
    }

    /**
     * Gets the value of the keyGroupMemberOrder property.
     * 
     * @return
     *     possible object is
     *     {@link KeyGroupMemberOrder }
     *     
     */
    public KeyGroupMemberOrder getKeyGroupMemberOrder() {
        return keyGroupMemberOrder;
    }

    /**
     * Sets the value of the keyGroupMemberOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyGroupMemberOrder }
     *     
     */
    public void setKeyGroupMemberOrder(KeyGroupMemberOrder value) {
        this.keyGroupMemberOrder = value;
    }

}
