//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Key_Group_Type"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Relationship_Ref" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Schema_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Comment" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Logical_Only" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Generate_As_Constraint"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Do_Not_Generate"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Key_Group_Members_Order_Ref_Array" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Constraint_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Unique"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Index_Members_Order_Ref_Array" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name_Qualifier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "longId",
    "ownerPath",
    "keyGroupType",
    "relationshipRef",
    "schemaName",
    "comment",
    "isLogicalOnly",
    "physicalName",
    "generateAsConstraint",
    "dependentObjectsRefArray",
    "doNotGenerate",
    "keyGroupMembersOrderRefArray",
    "constraintName",
    "isUnique",
    "indexMembersOrderRefArray",
    "userFormattedName",
    "userFormattedPhysicalName",
    "nameQualifier"
})
@XmlRootElement(name = "Key_GroupProps")
public class KeyGroupProps {

    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Key_Group_Type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String keyGroupType;
    @XmlElement(name = "Relationship_Ref")
    protected String relationshipRef;
    @XmlElement(name = "Schema_Name", required = true)
    protected SchemaName schemaName;
    @XmlElement(name = "Comment")
    protected Comment comment;
    @XmlElement(name = "Is_Logical_Only")
    protected Boolean isLogicalOnly;
    @XmlElement(name = "Physical_Name", required = true)
    protected PhysicalName physicalName;
    @XmlElement(name = "Generate_As_Constraint")
    protected boolean generateAsConstraint;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "Do_Not_Generate", required = true)
    protected DoNotGenerate doNotGenerate;
    @XmlElement(name = "Key_Group_Members_Order_Ref_Array")
    protected KeyGroupMembersOrderRefArray keyGroupMembersOrderRefArray;
    @XmlElement(name = "Constraint_Name", required = true)
    protected ConstraintName constraintName;
    @XmlElement(name = "Is_Unique", required = true)
    protected IsUnique isUnique;
    @XmlElement(name = "Index_Members_Order_Ref_Array")
    protected IndexMembersOrderRefArray indexMembersOrderRefArray;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;
    @XmlElement(name = "Name_Qualifier", required = true)
    protected NameQualifier nameQualifier;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the keyGroupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyGroupType() {
        return keyGroupType;
    }

    /**
     * Sets the value of the keyGroupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyGroupType(String value) {
        this.keyGroupType = value;
    }

    /**
     * Gets the value of the relationshipRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipRef() {
        return relationshipRef;
    }

    /**
     * Sets the value of the relationshipRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipRef(String value) {
        this.relationshipRef = value;
    }

    /**
     * Gets the value of the schemaName property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaName }
     *     
     */
    public SchemaName getSchemaName() {
        return schemaName;
    }

    /**
     * Sets the value of the schemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaName }
     *     
     */
    public void setSchemaName(SchemaName value) {
        this.schemaName = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the isLogicalOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLogicalOnly() {
        return isLogicalOnly;
    }

    /**
     * Sets the value of the isLogicalOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLogicalOnly(Boolean value) {
        this.isLogicalOnly = value;
    }

    /**
     * Gets the value of the physicalName property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalName }
     *     
     */
    public PhysicalName getPhysicalName() {
        return physicalName;
    }

    /**
     * Sets the value of the physicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalName }
     *     
     */
    public void setPhysicalName(PhysicalName value) {
        this.physicalName = value;
    }

    /**
     * Gets the value of the generateAsConstraint property.
     * 
     */
    public boolean isGenerateAsConstraint() {
        return generateAsConstraint;
    }

    /**
     * Sets the value of the generateAsConstraint property.
     * 
     */
    public void setGenerateAsConstraint(boolean value) {
        this.generateAsConstraint = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the doNotGenerate property.
     * 
     * @return
     *     possible object is
     *     {@link DoNotGenerate }
     *     
     */
    public DoNotGenerate getDoNotGenerate() {
        return doNotGenerate;
    }

    /**
     * Sets the value of the doNotGenerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoNotGenerate }
     *     
     */
    public void setDoNotGenerate(DoNotGenerate value) {
        this.doNotGenerate = value;
    }

    /**
     * Gets the value of the keyGroupMembersOrderRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link KeyGroupMembersOrderRefArray }
     *     
     */
    public KeyGroupMembersOrderRefArray getKeyGroupMembersOrderRefArray() {
        return keyGroupMembersOrderRefArray;
    }

    /**
     * Sets the value of the keyGroupMembersOrderRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyGroupMembersOrderRefArray }
     *     
     */
    public void setKeyGroupMembersOrderRefArray(KeyGroupMembersOrderRefArray value) {
        this.keyGroupMembersOrderRefArray = value;
    }

    /**
     * Gets the value of the constraintName property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintName }
     *     
     */
    public ConstraintName getConstraintName() {
        return constraintName;
    }

    /**
     * Sets the value of the constraintName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintName }
     *     
     */
    public void setConstraintName(ConstraintName value) {
        this.constraintName = value;
    }

    /**
     * Gets the value of the isUnique property.
     * 
     * @return
     *     possible object is
     *     {@link IsUnique }
     *     
     */
    public IsUnique getIsUnique() {
        return isUnique;
    }

    /**
     * Sets the value of the isUnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsUnique }
     *     
     */
    public void setIsUnique(IsUnique value) {
        this.isUnique = value;
    }

    /**
     * Gets the value of the indexMembersOrderRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link IndexMembersOrderRefArray }
     *     
     */
    public IndexMembersOrderRefArray getIndexMembersOrderRefArray() {
        return indexMembersOrderRefArray;
    }

    /**
     * Sets the value of the indexMembersOrderRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexMembersOrderRefArray }
     *     
     */
    public void setIndexMembersOrderRefArray(IndexMembersOrderRefArray value) {
        this.indexMembersOrderRefArray = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

    /**
     * Gets the value of the nameQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link NameQualifier }
     *     
     */
    public NameQualifier getNameQualifier() {
        return nameQualifier;
    }

    /**
     * Sets the value of the nameQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameQualifier }
     *     
     */
    public void setNameQualifier(NameQualifier value) {
        this.nameQualifier = value;
    }

}
