//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Author"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Object_Order"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Proxy_Short_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Border"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Bottom_Margin"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Color"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Footer"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Header"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Left_Margin"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Orientation"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Paper_Size"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Paper_Source" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Printer_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Range"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Right_Margin"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Scaling"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Top_Margin"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Paper_Dimensions"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Print_Paper_Form_Type"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Creation_Time"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Modification_Time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "longId",
    "ownerPath",
    "author",
    "objectOrder",
    "dependentObjectsRefArray",
    "proxyShortId",
    "printBorder",
    "printBottomMargin",
    "printColor",
    "printFooter",
    "printHeader",
    "printLeftMargin",
    "printOrientation",
    "printPaperSize",
    "printPaperSource",
    "printPrinterName",
    "printRange",
    "printRightMargin",
    "printScaling",
    "printTopMargin",
    "userFormattedName",
    "userFormattedPhysicalName",
    "printPaperDimensions",
    "printPaperFormType",
    "creationTime",
    "modificationTime"
})
@XmlRootElement(name = "Stored_DisplayProps")
public class StoredDisplayProps {

    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Author", required = true)
    protected String author;
    @XmlElement(name = "Object_Order", required = true)
    protected BigInteger objectOrder;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "Proxy_Short_Id", required = true)
    protected ProxyShortId proxyShortId;
    @XmlElement(name = "Print_Border")
    protected boolean printBorder;
    @XmlElement(name = "Print_Bottom_Margin", required = true)
    protected BigInteger printBottomMargin;
    @XmlElement(name = "Print_Color")
    protected boolean printColor;
    @XmlElement(name = "Print_Footer", required = true)
    protected String printFooter;
    @XmlElement(name = "Print_Header", required = true)
    protected String printHeader;
    @XmlElement(name = "Print_Left_Margin", required = true)
    protected BigInteger printLeftMargin;
    @XmlElement(name = "Print_Orientation", required = true)
    protected BigInteger printOrientation;
    @XmlElement(name = "Print_Paper_Size", required = true)
    protected String printPaperSize;
    @XmlElement(name = "Print_Paper_Source")
    protected BigInteger printPaperSource;
    @XmlElement(name = "Print_Printer_Name", required = true)
    protected String printPrinterName;
    @XmlElement(name = "Print_Range", required = true)
    protected BigInteger printRange;
    @XmlElement(name = "Print_Right_Margin", required = true)
    protected BigInteger printRightMargin;
    @XmlElement(name = "Print_Scaling", required = true)
    protected BigInteger printScaling;
    @XmlElement(name = "Print_Top_Margin", required = true)
    protected BigInteger printTopMargin;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;
    @XmlElement(name = "Print_Paper_Dimensions", required = true)
    protected BigDecimal printPaperDimensions;
    @XmlElement(name = "Print_Paper_Form_Type", required = true)
    protected BigInteger printPaperFormType;
    @XmlElement(name = "Creation_Time", required = true)
    protected String creationTime;
    @XmlElement(name = "Modification_Time", required = true)
    protected String modificationTime;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the objectOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectOrder() {
        return objectOrder;
    }

    /**
     * Sets the value of the objectOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectOrder(BigInteger value) {
        this.objectOrder = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the proxyShortId property.
     * 
     * @return
     *     possible object is
     *     {@link ProxyShortId }
     *     
     */
    public ProxyShortId getProxyShortId() {
        return proxyShortId;
    }

    /**
     * Sets the value of the proxyShortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxyShortId }
     *     
     */
    public void setProxyShortId(ProxyShortId value) {
        this.proxyShortId = value;
    }

    /**
     * Gets the value of the printBorder property.
     * 
     */
    public boolean isPrintBorder() {
        return printBorder;
    }

    /**
     * Sets the value of the printBorder property.
     * 
     */
    public void setPrintBorder(boolean value) {
        this.printBorder = value;
    }

    /**
     * Gets the value of the printBottomMargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintBottomMargin() {
        return printBottomMargin;
    }

    /**
     * Sets the value of the printBottomMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintBottomMargin(BigInteger value) {
        this.printBottomMargin = value;
    }

    /**
     * Gets the value of the printColor property.
     * 
     */
    public boolean isPrintColor() {
        return printColor;
    }

    /**
     * Sets the value of the printColor property.
     * 
     */
    public void setPrintColor(boolean value) {
        this.printColor = value;
    }

    /**
     * Gets the value of the printFooter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintFooter() {
        return printFooter;
    }

    /**
     * Sets the value of the printFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintFooter(String value) {
        this.printFooter = value;
    }

    /**
     * Gets the value of the printHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintHeader() {
        return printHeader;
    }

    /**
     * Sets the value of the printHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintHeader(String value) {
        this.printHeader = value;
    }

    /**
     * Gets the value of the printLeftMargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintLeftMargin() {
        return printLeftMargin;
    }

    /**
     * Sets the value of the printLeftMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintLeftMargin(BigInteger value) {
        this.printLeftMargin = value;
    }

    /**
     * Gets the value of the printOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintOrientation() {
        return printOrientation;
    }

    /**
     * Sets the value of the printOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintOrientation(BigInteger value) {
        this.printOrientation = value;
    }

    /**
     * Gets the value of the printPaperSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintPaperSize() {
        return printPaperSize;
    }

    /**
     * Sets the value of the printPaperSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintPaperSize(String value) {
        this.printPaperSize = value;
    }

    /**
     * Gets the value of the printPaperSource property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintPaperSource() {
        return printPaperSource;
    }

    /**
     * Sets the value of the printPaperSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintPaperSource(BigInteger value) {
        this.printPaperSource = value;
    }

    /**
     * Gets the value of the printPrinterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintPrinterName() {
        return printPrinterName;
    }

    /**
     * Sets the value of the printPrinterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintPrinterName(String value) {
        this.printPrinterName = value;
    }

    /**
     * Gets the value of the printRange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintRange() {
        return printRange;
    }

    /**
     * Sets the value of the printRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintRange(BigInteger value) {
        this.printRange = value;
    }

    /**
     * Gets the value of the printRightMargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintRightMargin() {
        return printRightMargin;
    }

    /**
     * Sets the value of the printRightMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintRightMargin(BigInteger value) {
        this.printRightMargin = value;
    }

    /**
     * Gets the value of the printScaling property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintScaling() {
        return printScaling;
    }

    /**
     * Sets the value of the printScaling property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintScaling(BigInteger value) {
        this.printScaling = value;
    }

    /**
     * Gets the value of the printTopMargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintTopMargin() {
        return printTopMargin;
    }

    /**
     * Sets the value of the printTopMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintTopMargin(BigInteger value) {
        this.printTopMargin = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

    /**
     * Gets the value of the printPaperDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrintPaperDimensions() {
        return printPaperDimensions;
    }

    /**
     * Sets the value of the printPaperDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrintPaperDimensions(BigDecimal value) {
        this.printPaperDimensions = value;
    }

    /**
     * Gets the value of the printPaperFormType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrintPaperFormType() {
        return printPaperFormType;
    }

    /**
     * Sets the value of the printPaperFormType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrintPaperFormType(BigInteger value) {
        this.printPaperFormType = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the modificationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationTime() {
        return modificationTime;
    }

    /**
     * Sets the value of the modificationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationTime(String value) {
        this.modificationTime = value;
    }

}
