//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Validation_RuleProps"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Valid_Value_Groups" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validationRuleProps",
    "validValueGroups"
})
@XmlRootElement(name = "Validation_Rule")
public class ValidationRule {

    @XmlElement(name = "Validation_RuleProps", required = true)
    protected ValidationRuleProps validationRuleProps;
    @XmlElement(name = "Valid_Value_Groups")
    protected ValidValueGroups validValueGroups;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the validationRuleProps property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationRuleProps }
     *     
     */
    public ValidationRuleProps getValidationRuleProps() {
        return validationRuleProps;
    }

    /**
     * Sets the value of the validationRuleProps property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationRuleProps }
     *     
     */
    public void setValidationRuleProps(ValidationRuleProps value) {
        this.validationRuleProps = value;
    }

    /**
     * Gets the value of the validValueGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ValidValueGroups }
     *     
     */
    public ValidValueGroups getValidValueGroups() {
        return validValueGroups;
    }

    /**
     * Sets the value of the validValueGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidValueGroups }
     *     
     */
    public void setValidValueGroups(ValidValueGroups value) {
        this.validValueGroups = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
