//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 10:07:29 PM BRST 
//

package com.indracompany.jaxb.note.column;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.indracompany.to.EntityTO;
import com.indracompany.type.ValidatorType;

/**
 * <p>
 * Java class for NoteValidator complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="NoteValidator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="length" type="{}Length" minOccurs="0"/>
 *         &lt;element name="size" type="{}Size" minOccurs="0"/>
 *         &lt;element name="notNull" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="notEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="min" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="past" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="future" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cnpj" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cpf" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ipOrMask" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoteValidator", propOrder = { "length", "size", "notNull",
		"notEmpty", "min", "max", "pattern", "past", "future", "email",
		"valid", "cnpj", "cpf", "ipOrMask", "validators" })
public class NoteValidator {

	private static final String ANNOTATION = "@";

	protected Length length;
	protected Size size;
	protected Boolean notNull;
	protected Boolean notEmpty;
	protected Integer min;
	protected Integer max;
	protected String pattern;
	protected Boolean past;
	protected Boolean future;
	protected Boolean email;
	protected Boolean valid;
	protected Boolean cnpj;
	protected Boolean cpf;
	protected Boolean ipOrMask;
	protected List<String> validators;

	/**
	 * Gets the value of the length property.
	 * 
	 * @return possible object is {@link Length }
	 * 
	 */
	public Length getLength() {
		return length;
	}

	/**
	 * Sets the value of the length property.
	 * 
	 * @param value
	 *            allowed object is {@link Length }
	 * 
	 */
	public void setLength(Length value) {
		this.length = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link Size }
	 * 
	 */
	public Size getSize() {
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link Size }
	 * 
	 */
	public void setSize(Size value) {
		this.size = value;
	}

	/**
	 * Gets the value of the notNull property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isNotNull() {
		return notNull;
	}

	/**
	 * Sets the value of the notNull property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setNotNull(Boolean value) {
		this.notNull = value;
	}

	/**
	 * Gets the value of the notEmpty property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isNotEmpty() {
		return notEmpty;
	}

	/**
	 * Sets the value of the notEmpty property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setNotEmpty(Boolean value) {
		this.notEmpty = value;
	}

	/**
	 * Gets the value of the min property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getMin() {
		return min;
	}

	/**
	 * Sets the value of the min property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMin(Integer value) {
		this.min = value;
	}

	/**
	 * Gets the value of the max property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getMax() {
		return max;
	}

	/**
	 * Sets the value of the max property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMax(Integer value) {
		this.max = value;
	}

	/**
	 * Gets the value of the pattern property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPattern() {
		return pattern;
	}

	/**
	 * Sets the value of the pattern property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPattern(String value) {
		this.pattern = value;
	}

	/**
	 * Gets the value of the past property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isPast() {
		return past;
	}

	/**
	 * Sets the value of the past property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setPast(Boolean value) {
		this.past = value;
	}

	/**
	 * Gets the value of the future property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isFuture() {
		return future;
	}

	/**
	 * Sets the value of the future property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setFuture(Boolean value) {
		this.future = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isEmail() {
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setEmail(Boolean value) {
		this.email = value;
	}

	/**
	 * Gets the value of the valid property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isValid() {
		return valid;
	}

	/**
	 * Sets the value of the valid property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setValid(Boolean value) {
		this.valid = value;
	}

	/**
	 * Gets the value of the cnpj property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isCnpj() {
		return cnpj;
	}

	/**
	 * Sets the value of the cnpj property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setCnpj(Boolean value) {
		this.cnpj = value;
	}

	/**
	 * Gets the value of the cpf property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isCpf() {
		return cpf;
	}

	/**
	 * Sets the value of the cpf property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setCpf(Boolean value) {
		this.cpf = value;
	}

	/**
	 * Gets the value of the ipOrMask property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIpOrMask() {
		return ipOrMask;
	}

	/**
	 * Sets the value of the ipOrMask property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIpOrMask(Boolean value) {
		this.ipOrMask = value;
	}

	/**
	 * @return Set<String>
	 */
	public List<String> getValidators() {
		if (this.validators == null) {
			this.validators = new ArrayList<String>();
		}
		return validators;
	}

	public void generateValidator(EntityTO entityTO) {
		if (this.isNotNull() != null) {
			this.getValidators().add(
					ANNOTATION + ValidatorType.NotNull.toString());
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.NotNull.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.NotNull.getValue());
		}
//		if (this.isNotEmpty() != null) {
//			this.getValidators().add(
//					ANNOTATION + ValidatorType.NotEmpty.toString());
//			if (!entityTO.getPackageValidatorAplication().contains(
//					ValidatorType.NotEmpty.getValue()))
//				entityTO.getPackageValidatorAplication().add(
//						ValidatorType.NotEmpty.getValue());
//		}
		if (this.isPast() != null) {
			this.getValidators()
					.add(ANNOTATION + ValidatorType.Past.toString());
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Past.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.Past.getValue());
		}
		if (this.isFuture() != null) {
			this.getValidators().add(
					ANNOTATION + ValidatorType.Future.toString());
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Future.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.Future.getValue());
		}
		if (this.isValid() != null) {
			this.getValidators().add(
					ANNOTATION + ValidatorType.Valid.toString());
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Valid.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.Valid.getValue());
		}
		if (this.isCnpj() != null) {
			this.getValidators()
					.add(ANNOTATION + ValidatorType.CNPJ.toString());
			if (!entityTO.getPackageValidatorAplication().contains(
					ValidatorType.CNPJ.getValue()))
				entityTO.getPackageValidatorAplication().add(
						ValidatorType.CNPJ.getValue());
		}
		if (this.isCpf() != null) {
			this.getValidators().add(ANNOTATION + ValidatorType.CPF.toString());
			if (!entityTO.getPackageValidatorAplication().contains(
					ValidatorType.CPF.getValue()))
				entityTO.getPackageValidatorAplication().add(
						ValidatorType.CPF.getValue());
		}
		if (this.isIpOrMask() != null) {
			this.getValidators().add(
					ANNOTATION + ValidatorType.IpOrMask.toString());
			if (!entityTO.getPackageValidatorAplication().contains(
					ValidatorType.IpOrMask.getValue()))
				entityTO.getPackageValidatorAplication().add(
						ValidatorType.IpOrMask.getValue());
		}
		if (this.getMin() != null) {
			this.getValidators().add("@Min(value = " + this.getMin() + ")");
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Min.getValue()))
				entityTO.getPackageValidator()
						.add(ValidatorType.Min.getValue());
		}
		if (this.getMax() != null) {
			this.getValidators().add("@Max(value = " + this.getMax() + ")");
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Max.getValue()))
				entityTO.getPackageValidator()
						.add(ValidatorType.Max.getValue());
		}
		if (this.getPattern() != null) {
			this.getValidators().add(
					"@Pattern(regexp = \"" + this.getPattern() + "\")");
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Pattern.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.Pattern.getValue());
		}
		if (this.getLength() != null) {
			this.getValidators().add(
					"@Length(min = " + this.getLength().getMin() + ", max = "
							+ this.getLength().getMax() + ")");
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Length.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.Length.getValue());
		}
		if (this.getSize() != null) {
			this.getValidators().add(
					"@Size(min  = " + this.getSize().getMin() + ", max = "
							+ this.getSize().getMax() + ")");
			if (!entityTO.getPackageValidator().contains(
					ValidatorType.Size.getValue()))
				entityTO.getPackageValidator().add(
						ValidatorType.Size.getValue());
		}
	}
}
