//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.26 at 10:06:28 PM BRST 
//


package com.indracompany.jaxb.note.column;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.indracompany.jaxb.note.column package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoteColumnConfiguration_QNAME = new QName("", "noteColumnConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.indracompany.jaxb.note.column
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Size }
     * 
     */
    public Size createSize() {
        return new Size();
    }

    /**
     * Create an instance of {@link NoteColumnConfiguration }
     * 
     */
    public NoteColumnConfiguration createNoteColumnConfiguration() {
        return new NoteColumnConfiguration();
    }

    /**
     * Create an instance of {@link Length }
     * 
     */
    public Length createLength() {
        return new Length();
    }

    /**
     * Create an instance of {@link NoteORM }
     * 
     */
    public NoteORM createNoteORM() {
        return new NoteORM();
    }

    /**
     * Create an instance of {@link Display }
     * 
     */
    public Display createDisplay() {
        return new Display();
    }

    /**
     * Create an instance of {@link NoteValidator }
     * 
     */
    public NoteValidator createNoteValidator() {
        return new NoteValidator();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteColumnConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "noteColumnConfiguration")
    public JAXBElement<NoteColumnConfiguration> createNoteColumnConfiguration(NoteColumnConfiguration value) {
        return new JAXBElement<NoteColumnConfiguration>(_NoteColumnConfiguration_QNAME, NoteColumnConfiguration.class, null, value);
    }

}
