//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.26 at 10:06:28 PM BRST 
//


package com.indracompany.jaxb.note.column;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCascade.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCascade">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALL"/>
 *     &lt;enumeration value="DETACH"/>
 *     &lt;enumeration value="MERGE"/>
 *     &lt;enumeration value="PERSIST"/>
 *     &lt;enumeration value="REFRESH"/>
 *     &lt;enumeration value="REMOVE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeCascade")
@XmlEnum
public enum TypeCascade {

    ALL,
    DETACH,
    MERGE,
    PERSIST,
    REFRESH,
    REMOVE;

    public String value() {
        return name();
    }

    public static TypeCascade fromValue(String v) {
        return valueOf(v);
    }

}
