//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.29 at 04:59:50 AM BRST 
//


package com.indracompany.jaxb.note.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.indracompany.jaxb.note.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoteEntityConfiguration_QNAME = new QName("", "noteEntityConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.indracompany.jaxb.note.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NoteEntityConfiguration }
     * 
     */
    public NoteEntityConfiguration createNoteEntityConfiguration() {
        return new NoteEntityConfiguration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteEntityConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "noteEntityConfiguration")
    public JAXBElement<NoteEntityConfiguration> createNoteEntityConfiguration(NoteEntityConfiguration value) {
        return new JAXBElement<NoteEntityConfiguration>(_NoteEntityConfiguration_QNAME, NoteEntityConfiguration.class, null, value);
    }

}
