//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.em2data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Report_Option_Set_Enabled"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Report_Option_Set_Multivalued"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Report_Option_Set_Option_Deprecated"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Report_Option_Set_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "longId",
    "reportOptionSetEnabled",
    "reportOptionSetMultivalued",
    "reportOptionSetOptionDeprecated",
    "reportOptionSetType"
})
@XmlRootElement(name = "Forward_Engineer_Options_SetProps")
public class ForwardEngineerOptionsSetProps {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Report_Option_Set_Enabled")
    protected boolean reportOptionSetEnabled;
    @XmlElement(name = "Report_Option_Set_Multivalued")
    protected boolean reportOptionSetMultivalued;
    @XmlElement(name = "Report_Option_Set_Option_Deprecated", required = true)
    protected BigInteger reportOptionSetOptionDeprecated;
    @XmlElement(name = "Report_Option_Set_Type", required = true)
    protected BigInteger reportOptionSetType;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the reportOptionSetEnabled property.
     * 
     */
    public boolean isReportOptionSetEnabled() {
        return reportOptionSetEnabled;
    }

    /**
     * Sets the value of the reportOptionSetEnabled property.
     * 
     */
    public void setReportOptionSetEnabled(boolean value) {
        this.reportOptionSetEnabled = value;
    }

    /**
     * Gets the value of the reportOptionSetMultivalued property.
     * 
     */
    public boolean isReportOptionSetMultivalued() {
        return reportOptionSetMultivalued;
    }

    /**
     * Sets the value of the reportOptionSetMultivalued property.
     * 
     */
    public void setReportOptionSetMultivalued(boolean value) {
        this.reportOptionSetMultivalued = value;
    }

    /**
     * Gets the value of the reportOptionSetOptionDeprecated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReportOptionSetOptionDeprecated() {
        return reportOptionSetOptionDeprecated;
    }

    /**
     * Sets the value of the reportOptionSetOptionDeprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReportOptionSetOptionDeprecated(BigInteger value) {
        this.reportOptionSetOptionDeprecated = value;
    }

    /**
     * Gets the value of the reportOptionSetType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReportOptionSetType() {
        return reportOptionSetType;
    }

    /**
     * Sets the value of the reportOptionSetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReportOptionSetType(BigInteger value) {
        this.reportOptionSetType = value;
    }

}
