//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.em2data;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ca.erwin.em2data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DisplayUngeneratedRelationships_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Ungenerated_Relationships");
    private final static QName _ShowMigratedAttributes_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Show_Migrated_Attributes");
    private final static QName _DisplayDomainLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Domain_Logical");
    private final static QName _DisplayViews_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Views");
    private final static QName _DisplayAttributeIcons_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Attribute_Icons");
    private final static QName _DisplayUngeneratedTables_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Ungenerated_Tables");
    private final static QName _NextUdpId_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Next_Udp_Id");
    private final static QName _DisplayDWIcons_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_DW_Icons");
    private final static QName _ShowPageGrid_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Show_Page_Grid");
    private final static QName _ObjectTypecode_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Object_Typecode");
    private final static QName _CurrentForwardEngineerOptionReportRef_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Current_Forward_Engineer_Option_Report_Ref");
    private final static QName _DisplayViewColumnExpressions_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_View_Column_Expressions");
    private final static QName _ReportOptionSetType_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Report_Option_Set_Type");
    private final static QName _DisplayDataTypePhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Data_Type_Physical");
    private final static QName _HorizontalScrollPosition_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Horizontal_Scroll_Position");
    private final static QName _DisplayRILogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_RI_Logical");
    private final static QName _DisplayRelationNamePhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Relation_Name_Physical");
    private final static QName _DisplayRIPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_RI_Physical");
    private final static QName _DisplayNotNull_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Not_Null");
    private final static QName _IsPhysicalViewActive_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Is_Physical_View_Active");
    private final static QName _DisplaySubcatName_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Subcat_Name");
    private final static QName _DisplayRelationNameLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Relation_Name_Logical");
    private final static QName _ForwardEngineerTemplateFileLocation_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Forward_Engineer_Template_File_Location");
    private final static QName _DisplayDanglingRels_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Dangling_Rels");
    private final static QName _ShadowOn_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Shadow_On");
    private final static QName _ZoomOptionDeprecated_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Zoom_Option_Deprecated");
    private final static QName _DisplayAKLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_AK_Logical");
    private final static QName _ReportOptionSetMultivalued_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Report_Option_Set_Multivalued");
    private final static QName _DisplayDataTypeLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Data_Type_Logical");
    private final static QName _CurrentStoredDisplayRef_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Current_Stored_Display_Ref");
    private final static QName _DisplayLevelLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "DisplayLevel_Logical");
    private final static QName _DisplayViewRelations_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_View_Relations");
    private final static QName _CurrentSubjectAreaRef_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Current_Subject_Area_Ref");
    private final static QName _DisplaySubtypeDiscriminatorLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Subtype_Discriminator_Logical");
    private final static QName _DisplayFKDesignatorLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_FK_Designator_Logical");
    private final static QName _DisplayRolenames_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Rolenames");
    private final static QName _LongId_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Long_Id");
    private final static QName _DisplayCardinalityLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Cardinality_Logical");
    private final static QName _DisplayDomainPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Domain_Physical");
    private final static QName _DisplayUngeneratedViews_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Ungenerated_Views");
    private final static QName _DisallowManualRelLayout_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Disallow_Manual_Rel_Layout");
    private final static QName _DisplayViewColumnNullOption_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_View_Column_Null_Option");
    private final static QName _ShadowHeight_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Shadow_Height");
    private final static QName _BuiltInId_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Built_In_Id");
    private final static QName _DisplayEntityIcons_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Entity_Icons");
    private final static QName _ShadowWidth_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Shadow_Width");
    private final static QName _AlignToGrid_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Align_To_Grid");
    private final static QName _LayoutGridVerticalSpacing_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Layout_Grid_Vertical_Spacing");
    private final static QName _Name_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Name");
    private final static QName _DisplayFKDesignatorPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_FK_Designator_Physical");
    private final static QName _DisplayViewColumnDataType_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_View_Column_Data_Type");
    private final static QName _LayoutGridHorizontalSpacing_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Layout_Grid_Horizontal_Spacing");
    private final static QName _ZoomLevel_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Zoom_Level");
    private final static QName _DisplayCardinalityPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_Cardinality_Physical");
    private final static QName _ReportOptionSetOptionDeprecated_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Report_Option_Set_Option_Deprecated");
    private final static QName _DisplayPKDesignatorPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_PK_Designator_Physical");
    private final static QName _DisplayPKDesignatorLogical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_PK_Designator_Logical");
    private final static QName _DisplayLevelPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "DisplayLevel_Physical");
    private final static QName _ReportOptionSetEnabled_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Report_Option_Set_Enabled");
    private final static QName _DisplayAKPhysical_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Display_AK_Physical");
    private final static QName _VerticalScrollPosition_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Vertical_Scroll_Position");
    private final static QName _UseDiagonalLines_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Use_Diagonal_Lines");
    private final static QName _ProhibitManualEntityResize_QNAME = new QName("http://www.ca.com/erwin/EM2data", "Prohibit_Manual_Entity_Resize");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ca.erwin.em2data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubjectAreaProxyObjectProps }
     * 
     */
    public SubjectAreaProxyObjectProps createSubjectAreaProxyObjectProps() {
        return new SubjectAreaProxyObjectProps();
    }

    /**
     * Create an instance of {@link ForwardEngineerOwnerOverride }
     * 
     */
    public ForwardEngineerOwnerOverride createForwardEngineerOwnerOverride() {
        return new ForwardEngineerOwnerOverride();
    }

    /**
     * Create an instance of {@link StoredDisplayProxyObjectProps }
     * 
     */
    public StoredDisplayProxyObjectProps createStoredDisplayProxyObjectProps() {
        return new StoredDisplayProxyObjectProps();
    }

    /**
     * Create an instance of {@link ExcludedAbstractEntityIdsArray }
     * 
     */
    public ExcludedAbstractEntityIdsArray createExcludedAbstractEntityIdsArray() {
        return new ExcludedAbstractEntityIdsArray();
    }

    /**
     * Create an instance of {@link ModelProxyObjectProps }
     * 
     */
    public ModelProxyObjectProps createModelProxyObjectProps() {
        return new ModelProxyObjectProps();
    }

    /**
     * Create an instance of {@link ForwardEngineerOptionsReportProps }
     * 
     */
    public ForwardEngineerOptionsReportProps createForwardEngineerOptionsReportProps() {
        return new ForwardEngineerOptionsReportProps();
    }

    /**
     * Create an instance of {@link SubjectAreaProxyObject }
     * 
     */
    public SubjectAreaProxyObject createSubjectAreaProxyObject() {
        return new SubjectAreaProxyObject();
    }

    /**
     * Create an instance of {@link ForwardEngineerOptionsSetProps }
     * 
     */
    public ForwardEngineerOptionsSetProps createForwardEngineerOptionsSetProps() {
        return new ForwardEngineerOptionsSetProps();
    }

    /**
     * Create an instance of {@link ForwardEngineerOptionsSetGroups }
     * 
     */
    public ForwardEngineerOptionsSetGroups createForwardEngineerOptionsSetGroups() {
        return new ForwardEngineerOptionsSetGroups();
    }

    /**
     * Create an instance of {@link ModelProxyObject }
     * 
     */
    public ModelProxyObject createModelProxyObject() {
        return new ModelProxyObject();
    }

    /**
     * Create an instance of {@link ForwardEngineerOwnerOverrideGroups }
     * 
     */
    public ForwardEngineerOwnerOverrideGroups createForwardEngineerOwnerOverrideGroups() {
        return new ForwardEngineerOwnerOverrideGroups();
    }

    /**
     * Create an instance of {@link StoredDisplayProxyObjectGroups }
     * 
     */
    public StoredDisplayProxyObjectGroups createStoredDisplayProxyObjectGroups() {
        return new StoredDisplayProxyObjectGroups();
    }

    /**
     * Create an instance of {@link SubjectAreaProxyObjectGroups }
     * 
     */
    public SubjectAreaProxyObjectGroups createSubjectAreaProxyObjectGroups() {
        return new SubjectAreaProxyObjectGroups();
    }

    /**
     * Create an instance of {@link OwnerName }
     * 
     */
    public OwnerName createOwnerName() {
        return new OwnerName();
    }

    /**
     * Create an instance of {@link ForwardEngineerOptionsReport }
     * 
     */
    public ForwardEngineerOptionsReport createForwardEngineerOptionsReport() {
        return new ForwardEngineerOptionsReport();
    }

    /**
     * Create an instance of {@link ForwardEngineerOwnerOverrideProps }
     * 
     */
    public ForwardEngineerOwnerOverrideProps createForwardEngineerOwnerOverrideProps() {
        return new ForwardEngineerOwnerOverrideProps();
    }

    /**
     * Create an instance of {@link ForwardEngineerOptionsReportGroups }
     * 
     */
    public ForwardEngineerOptionsReportGroups createForwardEngineerOptionsReportGroups() {
        return new ForwardEngineerOptionsReportGroups();
    }

    /**
     * Create an instance of {@link NextNameIdRelationship }
     * 
     */
    public NextNameIdRelationship createNextNameIdRelationship() {
        return new NextNameIdRelationship();
    }

    /**
     * Create an instance of {@link ProxiedObjectId }
     * 
     */
    public ProxiedObjectId createProxiedObjectId() {
        return new ProxiedObjectId();
    }

    /**
     * Create an instance of {@link NextNameIdEntity }
     * 
     */
    public NextNameIdEntity createNextNameIdEntity() {
        return new NextNameIdEntity();
    }

    /**
     * Create an instance of {@link StoredDisplayProxyObject }
     * 
     */
    public StoredDisplayProxyObject createStoredDisplayProxyObject() {
        return new StoredDisplayProxyObject();
    }

    /**
     * Create an instance of {@link ForwardEngineerOptionsSet }
     * 
     */
    public ForwardEngineerOptionsSet createForwardEngineerOptionsSet() {
        return new ForwardEngineerOptionsSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Ungenerated_Relationships")
    public JAXBElement<Boolean> createDisplayUngeneratedRelationships(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayUngeneratedRelationships_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Show_Migrated_Attributes")
    public JAXBElement<Boolean> createShowMigratedAttributes(Boolean value) {
        return new JAXBElement<Boolean>(_ShowMigratedAttributes_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Domain_Logical")
    public JAXBElement<Boolean> createDisplayDomainLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayDomainLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Views")
    public JAXBElement<Boolean> createDisplayViews(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayViews_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Attribute_Icons")
    public JAXBElement<Boolean> createDisplayAttributeIcons(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayAttributeIcons_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Ungenerated_Tables")
    public JAXBElement<Boolean> createDisplayUngeneratedTables(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayUngeneratedTables_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Next_Udp_Id")
    public JAXBElement<BigInteger> createNextUdpId(BigInteger value) {
        return new JAXBElement<BigInteger>(_NextUdpId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_DW_Icons")
    public JAXBElement<Boolean> createDisplayDWIcons(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayDWIcons_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Show_Page_Grid")
    public JAXBElement<Boolean> createShowPageGrid(Boolean value) {
        return new JAXBElement<Boolean>(_ShowPageGrid_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Object_Typecode")
    public JAXBElement<String> createObjectTypecode(String value) {
        return new JAXBElement<String>(_ObjectTypecode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Current_Forward_Engineer_Option_Report_Ref")
    public JAXBElement<String> createCurrentForwardEngineerOptionReportRef(String value) {
        return new JAXBElement<String>(_CurrentForwardEngineerOptionReportRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_View_Column_Expressions")
    public JAXBElement<Boolean> createDisplayViewColumnExpressions(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayViewColumnExpressions_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Report_Option_Set_Type")
    public JAXBElement<BigInteger> createReportOptionSetType(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReportOptionSetType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Data_Type_Physical")
    public JAXBElement<Boolean> createDisplayDataTypePhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayDataTypePhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Horizontal_Scroll_Position")
    public JAXBElement<BigInteger> createHorizontalScrollPosition(BigInteger value) {
        return new JAXBElement<BigInteger>(_HorizontalScrollPosition_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_RI_Logical")
    public JAXBElement<Boolean> createDisplayRILogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayRILogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Relation_Name_Physical")
    public JAXBElement<Boolean> createDisplayRelationNamePhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayRelationNamePhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_RI_Physical")
    public JAXBElement<Boolean> createDisplayRIPhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayRIPhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Not_Null")
    public JAXBElement<Boolean> createDisplayNotNull(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayNotNull_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Is_Physical_View_Active")
    public JAXBElement<Boolean> createIsPhysicalViewActive(Boolean value) {
        return new JAXBElement<Boolean>(_IsPhysicalViewActive_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Subcat_Name")
    public JAXBElement<BigInteger> createDisplaySubcatName(BigInteger value) {
        return new JAXBElement<BigInteger>(_DisplaySubcatName_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Relation_Name_Logical")
    public JAXBElement<Boolean> createDisplayRelationNameLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayRelationNameLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Forward_Engineer_Template_File_Location")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createForwardEngineerTemplateFileLocation(String value) {
        return new JAXBElement<String>(_ForwardEngineerTemplateFileLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Dangling_Rels")
    public JAXBElement<Boolean> createDisplayDanglingRels(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayDanglingRels_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Shadow_On")
    public JAXBElement<Boolean> createShadowOn(Boolean value) {
        return new JAXBElement<Boolean>(_ShadowOn_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Zoom_Option_Deprecated")
    public JAXBElement<BigInteger> createZoomOptionDeprecated(BigInteger value) {
        return new JAXBElement<BigInteger>(_ZoomOptionDeprecated_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_AK_Logical")
    public JAXBElement<Boolean> createDisplayAKLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayAKLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Report_Option_Set_Multivalued")
    public JAXBElement<Boolean> createReportOptionSetMultivalued(Boolean value) {
        return new JAXBElement<Boolean>(_ReportOptionSetMultivalued_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Data_Type_Logical")
    public JAXBElement<Boolean> createDisplayDataTypeLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayDataTypeLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Current_Stored_Display_Ref")
    public JAXBElement<String> createCurrentStoredDisplayRef(String value) {
        return new JAXBElement<String>(_CurrentStoredDisplayRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "DisplayLevel_Logical")
    public JAXBElement<BigInteger> createDisplayLevelLogical(BigInteger value) {
        return new JAXBElement<BigInteger>(_DisplayLevelLogical_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_View_Relations")
    public JAXBElement<Boolean> createDisplayViewRelations(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayViewRelations_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Current_Subject_Area_Ref")
    public JAXBElement<String> createCurrentSubjectAreaRef(String value) {
        return new JAXBElement<String>(_CurrentSubjectAreaRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Subtype_Discriminator_Logical")
    public JAXBElement<Boolean> createDisplaySubtypeDiscriminatorLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplaySubtypeDiscriminatorLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_FK_Designator_Logical")
    public JAXBElement<Boolean> createDisplayFKDesignatorLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayFKDesignatorLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Rolenames")
    public JAXBElement<Boolean> createDisplayRolenames(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayRolenames_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Long_Id")
    public JAXBElement<String> createLongId(String value) {
        return new JAXBElement<String>(_LongId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Cardinality_Logical")
    public JAXBElement<Boolean> createDisplayCardinalityLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayCardinalityLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Domain_Physical")
    public JAXBElement<Boolean> createDisplayDomainPhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayDomainPhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Ungenerated_Views")
    public JAXBElement<Boolean> createDisplayUngeneratedViews(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayUngeneratedViews_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Disallow_Manual_Rel_Layout")
    public JAXBElement<Boolean> createDisallowManualRelLayout(Boolean value) {
        return new JAXBElement<Boolean>(_DisallowManualRelLayout_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_View_Column_Null_Option")
    public JAXBElement<Boolean> createDisplayViewColumnNullOption(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayViewColumnNullOption_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Shadow_Height")
    public JAXBElement<BigInteger> createShadowHeight(BigInteger value) {
        return new JAXBElement<BigInteger>(_ShadowHeight_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Built_In_Id")
    public JAXBElement<BigInteger> createBuiltInId(BigInteger value) {
        return new JAXBElement<BigInteger>(_BuiltInId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Entity_Icons")
    public JAXBElement<Boolean> createDisplayEntityIcons(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayEntityIcons_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Shadow_Width")
    public JAXBElement<BigInteger> createShadowWidth(BigInteger value) {
        return new JAXBElement<BigInteger>(_ShadowWidth_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Align_To_Grid")
    public JAXBElement<Boolean> createAlignToGrid(Boolean value) {
        return new JAXBElement<Boolean>(_AlignToGrid_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Layout_Grid_Vertical_Spacing")
    public JAXBElement<BigInteger> createLayoutGridVerticalSpacing(BigInteger value) {
        return new JAXBElement<BigInteger>(_LayoutGridVerticalSpacing_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_FK_Designator_Physical")
    public JAXBElement<Boolean> createDisplayFKDesignatorPhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayFKDesignatorPhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_View_Column_Data_Type")
    public JAXBElement<Boolean> createDisplayViewColumnDataType(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayViewColumnDataType_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Layout_Grid_Horizontal_Spacing")
    public JAXBElement<BigInteger> createLayoutGridHorizontalSpacing(BigInteger value) {
        return new JAXBElement<BigInteger>(_LayoutGridHorizontalSpacing_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Zoom_Level")
    public JAXBElement<BigInteger> createZoomLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_ZoomLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_Cardinality_Physical")
    public JAXBElement<Boolean> createDisplayCardinalityPhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayCardinalityPhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Report_Option_Set_Option_Deprecated")
    public JAXBElement<BigInteger> createReportOptionSetOptionDeprecated(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReportOptionSetOptionDeprecated_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_PK_Designator_Physical")
    public JAXBElement<Boolean> createDisplayPKDesignatorPhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayPKDesignatorPhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_PK_Designator_Logical")
    public JAXBElement<Boolean> createDisplayPKDesignatorLogical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayPKDesignatorLogical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "DisplayLevel_Physical")
    public JAXBElement<BigInteger> createDisplayLevelPhysical(BigInteger value) {
        return new JAXBElement<BigInteger>(_DisplayLevelPhysical_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Report_Option_Set_Enabled")
    public JAXBElement<Boolean> createReportOptionSetEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_ReportOptionSetEnabled_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Display_AK_Physical")
    public JAXBElement<Boolean> createDisplayAKPhysical(Boolean value) {
        return new JAXBElement<Boolean>(_DisplayAKPhysical_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Vertical_Scroll_Position")
    public JAXBElement<BigInteger> createVerticalScrollPosition(BigInteger value) {
        return new JAXBElement<BigInteger>(_VerticalScrollPosition_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Use_Diagonal_Lines")
    public JAXBElement<Boolean> createUseDiagonalLines(Boolean value) {
        return new JAXBElement<Boolean>(_UseDiagonalLines_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ca.com/erwin/EM2data", name = "Prohibit_Manual_Entity_Resize")
    public JAXBElement<Boolean> createProhibitManualEntityResize(Boolean value) {
        return new JAXBElement<Boolean>(_ProhibitManualEntityResize_QNAME, Boolean.class, null, value);
    }

}
