//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.em2data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Proxied_Object_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/EM2data}Current_Stored_Display_Ref"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "longId",
    "proxiedObjectId",
    "currentStoredDisplayRef"
})
@XmlRootElement(name = "Subject_Area_Proxy_ObjectProps")
public class SubjectAreaProxyObjectProps {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Proxied_Object_Id", required = true)
    protected ProxiedObjectId proxiedObjectId;
    @XmlElement(name = "Current_Stored_Display_Ref", required = true)
    protected String currentStoredDisplayRef;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the proxiedObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link ProxiedObjectId }
     *     
     */
    public ProxiedObjectId getProxiedObjectId() {
        return proxiedObjectId;
    }

    /**
     * Sets the value of the proxiedObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxiedObjectId }
     *     
     */
    public void setProxiedObjectId(ProxiedObjectId value) {
        this.proxiedObjectId = value;
    }

    /**
     * Gets the value of the currentStoredDisplayRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentStoredDisplayRef() {
        return currentStoredDisplayRef;
    }

    /**
     * Sets the value of the currentStoredDisplayRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentStoredDisplayRef(String value) {
        this.currentStoredDisplayRef = value;
    }

}
