//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}AttributeProps"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}History_Information_Groups" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Check_Constraint_Usage_Groups" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Default_Constraint_Usage_Groups" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeProps",
    "historyInformationGroups",
    "checkConstraintUsageGroups",
    "defaultConstraintUsageGroups"
})
@XmlRootElement(name = "Attribute")
public class Attribute {

    @XmlElement(name = "AttributeProps", required = true)
    protected AttributeProps attributeProps;
    @XmlElement(name = "History_Information_Groups")
    protected HistoryInformationGroups historyInformationGroups;
    @XmlElement(name = "Check_Constraint_Usage_Groups")
    protected CheckConstraintUsageGroups checkConstraintUsageGroups;
    @XmlElement(name = "Default_Constraint_Usage_Groups")
    protected DefaultConstraintUsageGroups defaultConstraintUsageGroups;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the attributeProps property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeProps }
     *     
     */
    public AttributeProps getAttributeProps() {
        return attributeProps;
    }

    /**
     * Sets the value of the attributeProps property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeProps }
     *     
     */
    public void setAttributeProps(AttributeProps value) {
        this.attributeProps = value;
    }

    /**
     * Gets the value of the historyInformationGroups property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryInformationGroups }
     *     
     */
    public HistoryInformationGroups getHistoryInformationGroups() {
        return historyInformationGroups;
    }

    /**
     * Sets the value of the historyInformationGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryInformationGroups }
     *     
     */
    public void setHistoryInformationGroups(HistoryInformationGroups value) {
        this.historyInformationGroups = value;
    }

    /**
     * Gets the value of the checkConstraintUsageGroups property.
     * 
     * @return
     *     possible object is
     *     {@link CheckConstraintUsageGroups }
     *     
     */
    public CheckConstraintUsageGroups getCheckConstraintUsageGroups() {
        return checkConstraintUsageGroups;
    }

    /**
     * Sets the value of the checkConstraintUsageGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckConstraintUsageGroups }
     *     
     */
    public void setCheckConstraintUsageGroups(CheckConstraintUsageGroups value) {
        this.checkConstraintUsageGroups = value;
    }

    /**
     * Gets the value of the defaultConstraintUsageGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultConstraintUsageGroups }
     *     
     */
    public DefaultConstraintUsageGroups getDefaultConstraintUsageGroups() {
        return defaultConstraintUsageGroups;
    }

    /**
     * Sets the value of the defaultConstraintUsageGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultConstraintUsageGroups }
     *     
     */
    public void setDefaultConstraintUsageGroups(DefaultConstraintUsageGroups value) {
        this.defaultConstraintUsageGroups = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
