//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Locator"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Disposition"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Persistence_Unit_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Model_Type"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Target_Server"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Target_Server_Version"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Target_Server_Minor_Version"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Active_Model"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Hidden_Model"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Storage_Format"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locator",
    "disposition",
    "persistenceUnitId",
    "modelType",
    "targetServer",
    "targetServerVersion",
    "targetServerMinorVersion",
    "activeModel",
    "hiddenModel",
    "storageFormat"
})
@XmlRootElement(name = "ModelEnvProps")
public class ModelEnvProps {

    @XmlElement(name = "Locator", required = true)
    protected String locator;
    @XmlElement(name = "Disposition", required = true)
    protected Disposition disposition;
    @XmlElement(name = "Persistence_Unit_Id", required = true)
    protected String persistenceUnitId;
    @XmlElement(name = "Model_Type", required = true)
    protected BigInteger modelType;
    @XmlElement(name = "Target_Server", required = true)
    protected TargetServer targetServer;
    @XmlElement(name = "Target_Server_Version", required = true)
    protected BigInteger targetServerVersion;
    @XmlElement(name = "Target_Server_Minor_Version", required = true)
    protected BigInteger targetServerMinorVersion;
    @XmlElement(name = "Active_Model", required = true)
    protected BigInteger activeModel;
    @XmlElement(name = "Hidden_Model", required = true)
    protected BigInteger hiddenModel;
    @XmlElement(name = "Storage_Format", required = true)
    protected BigInteger storageFormat;

    /**
     * Gets the value of the locator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocator() {
        return locator;
    }

    /**
     * Sets the value of the locator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocator(String value) {
        this.locator = value;
    }

    /**
     * Gets the value of the disposition property.
     * 
     * @return
     *     possible object is
     *     {@link Disposition }
     *     
     */
    public Disposition getDisposition() {
        return disposition;
    }

    /**
     * Sets the value of the disposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Disposition }
     *     
     */
    public void setDisposition(Disposition value) {
        this.disposition = value;
    }

    /**
     * Gets the value of the persistenceUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersistenceUnitId() {
        return persistenceUnitId;
    }

    /**
     * Sets the value of the persistenceUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersistenceUnitId(String value) {
        this.persistenceUnitId = value;
    }

    /**
     * Gets the value of the modelType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModelType() {
        return modelType;
    }

    /**
     * Sets the value of the modelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModelType(BigInteger value) {
        this.modelType = value;
    }

    /**
     * Gets the value of the targetServer property.
     * 
     * @return
     *     possible object is
     *     {@link TargetServer }
     *     
     */
    public TargetServer getTargetServer() {
        return targetServer;
    }

    /**
     * Sets the value of the targetServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetServer }
     *     
     */
    public void setTargetServer(TargetServer value) {
        this.targetServer = value;
    }

    /**
     * Gets the value of the targetServerVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetServerVersion() {
        return targetServerVersion;
    }

    /**
     * Sets the value of the targetServerVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetServerVersion(BigInteger value) {
        this.targetServerVersion = value;
    }

    /**
     * Gets the value of the targetServerMinorVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetServerMinorVersion() {
        return targetServerMinorVersion;
    }

    /**
     * Sets the value of the targetServerMinorVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetServerMinorVersion(BigInteger value) {
        this.targetServerMinorVersion = value;
    }

    /**
     * Gets the value of the activeModel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActiveModel() {
        return activeModel;
    }

    /**
     * Sets the value of the activeModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActiveModel(BigInteger value) {
        this.activeModel = value;
    }

    /**
     * Gets the value of the hiddenModel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHiddenModel() {
        return hiddenModel;
    }

    /**
     * Sets the value of the hiddenModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHiddenModel(BigInteger value) {
        this.hiddenModel = value;
    }

    /**
     * Gets the value of the storageFormat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStorageFormat() {
        return storageFormat;
    }

    /**
     * Sets the value of the storageFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStorageFormat(BigInteger value) {
        this.storageFormat = value;
    }

}
