//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Percent_Free"/>
 *           &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Initial_Transactions"/>
 *           &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Tablespace_Ref"/>
 *           &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Initial_Extent_Size"/>
 *           &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Next_Extent_Size"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Min_Extents" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Buffer_Pool" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_No_Logging" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Max_Extent_Type" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Oracle_Tablespace_Usage_Type" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Do_Not_Generate"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "longId",
    "ownerPath",
    "oraclePercentFree",
    "oracleInitialTransactions",
    "oracleTablespaceRef",
    "oracleInitialExtentSize",
    "oracleNextExtentSize",
    "oracleMinExtents",
    "oracleBufferPool",
    "oracleNoLogging",
    "oracleMaxExtentType",
    "oracleTablespaceUsageType",
    "dependentObjectsRefArray",
    "doNotGenerate",
    "userFormattedName",
    "userFormattedPhysicalName"
})
@XmlRootElement(name = "Oracle_Attribute_StorageProps")
public class OracleAttributeStorageProps {

    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Oracle_Percent_Free")
    protected BigInteger oraclePercentFree;
    @XmlElement(name = "Oracle_Initial_Transactions")
    protected BigInteger oracleInitialTransactions;
    @XmlElement(name = "Oracle_Tablespace_Ref")
    protected String oracleTablespaceRef;
    @XmlElement(name = "Oracle_Initial_Extent_Size")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String oracleInitialExtentSize;
    @XmlElement(name = "Oracle_Next_Extent_Size")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String oracleNextExtentSize;
    @XmlElement(name = "Oracle_Min_Extents")
    protected BigInteger oracleMinExtents;
    @XmlElement(name = "Oracle_Buffer_Pool")
    protected BigInteger oracleBufferPool;
    @XmlElement(name = "Oracle_No_Logging")
    protected Boolean oracleNoLogging;
    @XmlElement(name = "Oracle_Max_Extent_Type")
    protected BigInteger oracleMaxExtentType;
    @XmlElement(name = "Oracle_Tablespace_Usage_Type")
    protected BigInteger oracleTablespaceUsageType;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "Do_Not_Generate", required = true)
    protected DoNotGenerate doNotGenerate;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the oraclePercentFree property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOraclePercentFree() {
        return oraclePercentFree;
    }

    /**
     * Sets the value of the oraclePercentFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOraclePercentFree(BigInteger value) {
        this.oraclePercentFree = value;
    }

    /**
     * Gets the value of the oracleInitialTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOracleInitialTransactions() {
        return oracleInitialTransactions;
    }

    /**
     * Sets the value of the oracleInitialTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOracleInitialTransactions(BigInteger value) {
        this.oracleInitialTransactions = value;
    }

    /**
     * Gets the value of the oracleTablespaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOracleTablespaceRef() {
        return oracleTablespaceRef;
    }

    /**
     * Sets the value of the oracleTablespaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOracleTablespaceRef(String value) {
        this.oracleTablespaceRef = value;
    }

    /**
     * Gets the value of the oracleInitialExtentSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOracleInitialExtentSize() {
        return oracleInitialExtentSize;
    }

    /**
     * Sets the value of the oracleInitialExtentSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOracleInitialExtentSize(String value) {
        this.oracleInitialExtentSize = value;
    }

    /**
     * Gets the value of the oracleNextExtentSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOracleNextExtentSize() {
        return oracleNextExtentSize;
    }

    /**
     * Sets the value of the oracleNextExtentSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOracleNextExtentSize(String value) {
        this.oracleNextExtentSize = value;
    }

    /**
     * Gets the value of the oracleMinExtents property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOracleMinExtents() {
        return oracleMinExtents;
    }

    /**
     * Sets the value of the oracleMinExtents property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOracleMinExtents(BigInteger value) {
        this.oracleMinExtents = value;
    }

    /**
     * Gets the value of the oracleBufferPool property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOracleBufferPool() {
        return oracleBufferPool;
    }

    /**
     * Sets the value of the oracleBufferPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOracleBufferPool(BigInteger value) {
        this.oracleBufferPool = value;
    }

    /**
     * Gets the value of the oracleNoLogging property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOracleNoLogging() {
        return oracleNoLogging;
    }

    /**
     * Sets the value of the oracleNoLogging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOracleNoLogging(Boolean value) {
        this.oracleNoLogging = value;
    }

    /**
     * Gets the value of the oracleMaxExtentType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOracleMaxExtentType() {
        return oracleMaxExtentType;
    }

    /**
     * Sets the value of the oracleMaxExtentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOracleMaxExtentType(BigInteger value) {
        this.oracleMaxExtentType = value;
    }

    /**
     * Gets the value of the oracleTablespaceUsageType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOracleTablespaceUsageType() {
        return oracleTablespaceUsageType;
    }

    /**
     * Sets the value of the oracleTablespaceUsageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOracleTablespaceUsageType(BigInteger value) {
        this.oracleTablespaceUsageType = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the doNotGenerate property.
     * 
     * @return
     *     possible object is
     *     {@link DoNotGenerate }
     *     
     */
    public DoNotGenerate getDoNotGenerate() {
        return doNotGenerate;
    }

    /**
     * Sets the value of the doNotGenerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoNotGenerate }
     *     
     */
    public void setDoNotGenerate(DoNotGenerate value) {
        this.doNotGenerate = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

}
