//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.13 at 10:21:45 PM BRST 
//


package com.ca.erwin.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Built_In_Id" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Definition"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Long_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Owner_Path"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Referenced_Entities_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Referenced_Relationships_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Author"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Filter_Dangling_Relationships_From_FE"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Object_Order"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Is_Main_Subject_Area" minOccurs="0"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Dependent_Objects_Ref_Array"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Proxy_Short_Id"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}User_Formatted_Physical_Name"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Creation_Time"/>
 *         &lt;element ref="{http://www.ca.com/erwin/data}Modification_Time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "builtInId",
    "definition",
    "name",
    "longId",
    "ownerPath",
    "referencedEntitiesRefArray",
    "referencedRelationshipsRefArray",
    "author",
    "filterDanglingRelationshipsFromFE",
    "objectOrder",
    "isMainSubjectArea",
    "dependentObjectsRefArray",
    "proxyShortId",
    "userFormattedName",
    "userFormattedPhysicalName",
    "creationTime",
    "modificationTime"
})
@XmlRootElement(name = "Subject_AreaProps")
public class SubjectAreaProps {

    @XmlElement(name = "Built_In_Id")
    protected BigInteger builtInId;
    @XmlElement(name = "Definition", required = true)
    protected Definition definition;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "Long_Id", required = true)
    protected String longId;
    @XmlElement(name = "Owner_Path", required = true)
    protected OwnerPath ownerPath;
    @XmlElement(name = "Referenced_Entities_Ref_Array", required = true)
    protected ReferencedEntitiesRefArray referencedEntitiesRefArray;
    @XmlElement(name = "Referenced_Relationships_Ref_Array", required = true)
    protected ReferencedRelationshipsRefArray referencedRelationshipsRefArray;
    @XmlElement(name = "Author", required = true)
    protected String author;
    @XmlElement(name = "Filter_Dangling_Relationships_From_FE")
    protected boolean filterDanglingRelationshipsFromFE;
    @XmlElement(name = "Object_Order", required = true)
    protected BigInteger objectOrder;
    @XmlElement(name = "Is_Main_Subject_Area")
    protected Boolean isMainSubjectArea;
    @XmlElement(name = "Dependent_Objects_Ref_Array", required = true)
    protected DependentObjectsRefArray dependentObjectsRefArray;
    @XmlElement(name = "Proxy_Short_Id", required = true)
    protected ProxyShortId proxyShortId;
    @XmlElement(name = "User_Formatted_Name", required = true)
    protected UserFormattedName userFormattedName;
    @XmlElement(name = "User_Formatted_Physical_Name", required = true)
    protected UserFormattedPhysicalName userFormattedPhysicalName;
    @XmlElement(name = "Creation_Time", required = true)
    protected String creationTime;
    @XmlElement(name = "Modification_Time", required = true)
    protected String modificationTime;

    /**
     * Gets the value of the builtInId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBuiltInId() {
        return builtInId;
    }

    /**
     * Sets the value of the builtInId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBuiltInId(BigInteger value) {
        this.builtInId = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link Definition }
     *     
     */
    public Definition getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition }
     *     
     */
    public void setDefinition(Definition value) {
        this.definition = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the longId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongId() {
        return longId;
    }

    /**
     * Sets the value of the longId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongId(String value) {
        this.longId = value;
    }

    /**
     * Gets the value of the ownerPath property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerPath }
     *     
     */
    public OwnerPath getOwnerPath() {
        return ownerPath;
    }

    /**
     * Sets the value of the ownerPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerPath }
     *     
     */
    public void setOwnerPath(OwnerPath value) {
        this.ownerPath = value;
    }

    /**
     * Gets the value of the referencedEntitiesRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedEntitiesRefArray }
     *     
     */
    public ReferencedEntitiesRefArray getReferencedEntitiesRefArray() {
        return referencedEntitiesRefArray;
    }

    /**
     * Sets the value of the referencedEntitiesRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedEntitiesRefArray }
     *     
     */
    public void setReferencedEntitiesRefArray(ReferencedEntitiesRefArray value) {
        this.referencedEntitiesRefArray = value;
    }

    /**
     * Gets the value of the referencedRelationshipsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedRelationshipsRefArray }
     *     
     */
    public ReferencedRelationshipsRefArray getReferencedRelationshipsRefArray() {
        return referencedRelationshipsRefArray;
    }

    /**
     * Sets the value of the referencedRelationshipsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedRelationshipsRefArray }
     *     
     */
    public void setReferencedRelationshipsRefArray(ReferencedRelationshipsRefArray value) {
        this.referencedRelationshipsRefArray = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the filterDanglingRelationshipsFromFE property.
     * 
     */
    public boolean isFilterDanglingRelationshipsFromFE() {
        return filterDanglingRelationshipsFromFE;
    }

    /**
     * Sets the value of the filterDanglingRelationshipsFromFE property.
     * 
     */
    public void setFilterDanglingRelationshipsFromFE(boolean value) {
        this.filterDanglingRelationshipsFromFE = value;
    }

    /**
     * Gets the value of the objectOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObjectOrder() {
        return objectOrder;
    }

    /**
     * Sets the value of the objectOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObjectOrder(BigInteger value) {
        this.objectOrder = value;
    }

    /**
     * Gets the value of the isMainSubjectArea property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMainSubjectArea() {
        return isMainSubjectArea;
    }

    /**
     * Sets the value of the isMainSubjectArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMainSubjectArea(Boolean value) {
        this.isMainSubjectArea = value;
    }

    /**
     * Gets the value of the dependentObjectsRefArray property.
     * 
     * @return
     *     possible object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public DependentObjectsRefArray getDependentObjectsRefArray() {
        return dependentObjectsRefArray;
    }

    /**
     * Sets the value of the dependentObjectsRefArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependentObjectsRefArray }
     *     
     */
    public void setDependentObjectsRefArray(DependentObjectsRefArray value) {
        this.dependentObjectsRefArray = value;
    }

    /**
     * Gets the value of the proxyShortId property.
     * 
     * @return
     *     possible object is
     *     {@link ProxyShortId }
     *     
     */
    public ProxyShortId getProxyShortId() {
        return proxyShortId;
    }

    /**
     * Sets the value of the proxyShortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxyShortId }
     *     
     */
    public void setProxyShortId(ProxyShortId value) {
        this.proxyShortId = value;
    }

    /**
     * Gets the value of the userFormattedName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedName }
     *     
     */
    public UserFormattedName getUserFormattedName() {
        return userFormattedName;
    }

    /**
     * Sets the value of the userFormattedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedName }
     *     
     */
    public void setUserFormattedName(UserFormattedName value) {
        this.userFormattedName = value;
    }

    /**
     * Gets the value of the userFormattedPhysicalName property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public UserFormattedPhysicalName getUserFormattedPhysicalName() {
        return userFormattedPhysicalName;
    }

    /**
     * Sets the value of the userFormattedPhysicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormattedPhysicalName }
     *     
     */
    public void setUserFormattedPhysicalName(UserFormattedPhysicalName value) {
        this.userFormattedPhysicalName = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the modificationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationTime() {
        return modificationTime;
    }

    /**
     * Sets the value of the modificationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationTime(String value) {
        this.modificationTime = value;
    }

}
